# Generated by Django 4.2.4 on 2023-10-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
